openapi: 3.0.3
info:
  title: My API
  version: 1.0.0
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
    AppClientAuth:
      type: apiKey
      in: header
      name: X-App-Secret
  schemas: {}
paths:
  /api/users:
    get:
      tags:
        - user
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    profile_image_url:
                      type: string
  /api/users/{id}:
    get:
      tags:
        - user
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  profile_image_url:
                    type: string
  /api/users/signup:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 20
                password:
                  type: string
                  minLength: 8
        required: true
      responses:
        "200":
          description: Default Response
  /api/auth/login:
    post:
      tags:
        - auth
      description: Logs in user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
        required: true
      responses:
        "200":
          description: Default Response
  /api/auth/refresh:
    post:
      tags:
        - auth
      description: Send refresh token in HttpOnly cookie called `refreshToken`
      security: &a1
        - BearerAuth: []
        - cookieAuth: []
      responses:
        "200":
          description: New access token
          content:
            application/json:
              schema:
                description: New access token
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                description: Unauthorized
  /api/auth/logout:
    post:
      tags:
        - auth
      description: Will log out the user
      security: *a1
      responses:
        "200":
          description: Default Response
  /api/users/me:
    delete:
      tags:
        - user
      description: Deletes the user
      security: &a2
        - BearerAuth: []
      responses:
        "200":
          description: Default Response
    patch:
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                profilePictureUrl:
                  type: string
              additionalProperties: false
      security: *a2
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /api/users/me/password:
    patch:
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - oldPassword
                - newPassword
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
                  minLength: 8
              additionalProperties: false
        required: true
      security: *a2
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /api/matches:
    post:
      tags:
        - matches
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - winner_id
                - loser_id
                - winner_score
                - loser_score
                - date
              properties:
                winner_id:
                  type: integer
                loser_id:
                  type: integer
                winner_score:
                  type: integer
                loser_score:
                  type: integer
                date:
                  type: string
                  format: date-time
        required: true
      responses:
        "200":
          description: Default Response
    get:
      tags:
        - matches
      responses:
        "200":
          description: Default Response
tags:
  - name: auth
    description: Auth endpoints
  - name: user
    description: User endpoints
  - name: matches
    description: Matches endpoints
