import crypto from "crypto";
import { generateTokens } from "../../services/authServices.js";

export default function login_2fa(server) {
	const opts = {
		schema: {
			description: "Verify a user's 2FA code sent during login",
			tags: ["auth"],
			querystring: {
				type: "object",
				required: ["twoFactorToken"],
				properties: {
					twoFactorToken: {
						type: "string",
						description: "Token generated by the login endpoint",
						example: "a3f9c8e2b4d74e0c9f...",
					},
				},
			},
			body: {
				type: "object",
				required: ["code"],
				description: "6-digit code sent to user email or app",
				properties: {
					code: { type: "string", minLength: 6, maxLength: 6 },
				},
			},
			response: {
				200: {
					description: "Login successful",
					type: "object",
					required: ["accessToken", "id"],
					properties: {
						accessToken: { type: "string" },
						id: { type: "integer" },
					},
				},

				401: {
					description: "Unauthorized: Invalid token or code",
					$ref: "errorResponse#",
				},
				500: {
					description: "Internal Server Error",
					$ref: "errorResponse#",
				},
				default: {
					description: "Unexpected error",
					$ref: "errorResponse#",
				},
			},
		},
	};
	server.post("/login/2fa", opts, async (req, reply) => {
		const { code } = req.body;
		const twoFactorToken = req.query.twoFactorToken;

		const user = server.db.prepare("SELECT code_hash_2fa, code_expires_2fa, id FROM users WHERE token_2fa = ?").get(twoFactorToken);
		if (!user) {
			return reply.status(401).send({ error: "Unauthorized", message: "Invalid token" });
		}
		if (user.code_expires_2fa < Date.now()) {
			return reply.status(401).send({ error: "Unauthorized", message: "Code expired" });
		}
		const inputHash = crypto.createHmac("sha256", process.env.OTP_SECRET).update(code).digest("hex");

		if (inputHash !== user.code_hash_2fa) {
			return reply.status(401).send({ error: "Unauthorized", message: "Invalid code" });
		}
		server.db
			.prepare(`UPDATE users SET code_hash_2fa = null,code_expires_2fa = null,token_2fa = null WHERE id = ?`)
			.run(user.id);
		return generateTokens(server, user, reply);
	});
}
